Maintenance/form builder upgrades
odyssy-automaton/pokemol-web pull request #1522
Opened 2021-10-27 08:38 UTC by jordanlesich

2021-10-27 08:40 UTC, jordanlesich commented
- Validation Overhaul
- Modifiers Overhaul
- MultiTX form
- React-Hook-Form nested data rebuild for FormBuilder

2021-10-27 18:48 UTC, skuhlmann requested changes

2021-10-27 18:48 UTC, skuhlmann commented on src/data/fields.js
> +    description: 'ssdfsd',
Should this be here?

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/checkGate.jsx
> +import { createRegisterOptions, useFormConditions } from '../utils/formBuilder';
import order

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/fieldWrapper.jsx
> +  //   if (!errors[name]) return;
tidy me up

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/abiInput.jsx
>    }, [targetContract]);
More of a question here i've been struggling with:

Should we add daochain in the dependency array? stuff from params should never trigger a re-render, but i think it's technically a dependency.

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/multiForm.jsx
> +import FormSection from './formSection';
import order

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/multiInput.jsx
> +    console.log('COMPONENT MOUNT');
tidy me up

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/paymentInput.jsx
> +// const getMaxBalance = (tokenData, tokenAddress) => {
clean up

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/paymentInput.jsx
> +    setValue('paymentRequested', token.balance / 10 ** token.decimals);
ah great fix. getMaxBalance was a bad issue

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/tributeInput.jsx
> +  console.log(`options`, options);
clean

2021-10-27 18:48 UTC, skuhlmann commented on src/formBuilder/txFormSection.jsx
> +import FormSection from './formSection';
import order

2021-10-27 18:48 UTC, skuhlmann commented on src/forms/lootGrab.jsx
> +//  Purge
PURGE

2021-10-27 18:48 UTC, skuhlmann commented on src/forms/memberProposal.jsx
> +//  Purge
AGAIN

2021-10-27 18:48 UTC, skuhlmann commented on src/forms/tradeProposal.jsx
> +// Purge
PURGE

2021-10-27 18:48 UTC, skuhlmann commented on src/utils/tokenValue.js
>  import { MolochService } from '../services/molochService';
Can we refactor to contract service? 

Not necessary immediately.

2021-10-27 18:48 UTC, skuhlmann commented on src/utils/txHelpers.js
> +// console.log(
can clean up

2021-10-27 18:48 UTC, skuhlmann commented on src/utils/validation.js
> +export const buildRHFvalFn = valString => {
function name is a little confusing!

2021-10-27 19:58 UTC, jordanlesich commented on src/data/fields.js
> +    description: 'ssdfsd',
lol

2021-10-27 20:00 UTC, jordanlesich commented on src/formBuilder/abiInput.jsx
>    }, [targetContract]);
Yep. Makes sense.

2021-10-27 20:00 UTC, jordanlesich commented on src/utils/tokenValue.js
>  import { MolochService } from '../services/molochService';
Oh, right. Yep.

2021-10-27 20:01 UTC, jordanlesich commented on src/utils/validation.js
> +export const buildRHFvalFn = valString => {
Right.

2021-10-27 21:18 UTC, skuhlmann commented on src/formBuilder/StepperForm.jsx
> +  const [localSteps, setLocalSteps] = useState(steps);
src/formBuilder/StepperForm.jsx
  Line 37:22:  'setLocalSteps' is assigned a value but never used  no-unused-vars

2021-10-28 17:39 UTC, jordanlesich commented on src/utils/tokenValue.js
>  import { MolochService } from '../services/molochService';
I'm going to hold out on this for a bit. Would require to me to test and make sure all things calling these utils are getting the right shape of data. But I think I need to go on a larger purge spree, so this should be prime pickens.

2021-10-28 17:46 UTC, jordanlesich commented on src/formBuilder/StepperForm.jsx
> +  const [localSteps, setLocalSteps] = useState(steps);
good catch.

2021-11-02 04:58 UTC, closed without merging