Fix/remove doc filters
odyssy-automaton/pokemol-web pull request #1853
Opened 2022-05-25 18:56 UTC by brossetti1

## GitHub Issue

https://github.com/HausDAO/daohaus-app/issues/1810

## Changes

- [x] Remove "IPFS" filter option
- [x] Remove "Chain" filter option

## Packages Added

N/A

## Checks

Before making your PR, please check the following:

- [X] Critical lint errors are resolved
- [X] App runs and builds locally

## Details

<img width="430" alt="Screen Shot 2022-05-25 at 12 52 09 PM" src="https://user-images.githubusercontent.com/5998100/170347065-d93f29b3-8bc4-499f-9a4a-2333e502770d.png">

2022-05-25 20:32 UTC, plor requested changes

2022-05-25 20:32 UTC, plor commented on src/components/proposalActions.jsx
> +                !proposal.isMinion && (
This got mixed in from your other PR. It doesn't belong in this PR.

2022-05-25 20:32 UTC, plor commented on src/data/formLegos/posterForms.js
> +  // },
I would suggest just deleting rather than commenting out.

2022-05-25 20:32 UTC, plor commented on src/data/txLegos/posterBoostTX.js
> +  // },
Same, if we need any of this back we can pull it from the history.

2022-05-26 15:05 UTC, brossetti1 commented on src/components/proposalActions.jsx
> +                !proposal.isMinion && (
whoops! sorry

2022-05-31 01:02 UTC, merged